Always Use linuxefi with DIB_BLOCK_DEVICE=efi
On centos 7 built with DIB_BLOCK_DEVICE=efi I am seeing:

  error: cant't find command linux
  error: cant't find command initrd

At the grub prompt.

We seem to force linux and initrd here:

https://github.com/openstack/diskimage-builder/blob/4a2b63e7f98aefbe9514a5dd710a05cb4b7e7a7c/diskimage_builder/elements/bootloader/finalise.d/50-bootloader#L185

Alternative solutions:

- Set GRUB_USE_LINUXEFI in /etc/default grub
- Install grub with the linux module i.e --modules="$modules linux"

Change-Id: I97a904df9bb016ad83ecd4ff149776f051cbfa45
(cherry picked from commit cf6c48b398152c9e2d26795549ac910cb11d5958)